export interface ResumeData {
  header: {
    name: string;
    phone: string;
    email: string;
    website: string;
    linkedin: string;
    github: string;
    leetcode: string;
  };
  summary: string;
  skills: {
    label: string;
    items: string;
  }[];
  experience: {
    company: string;
    date: string;
    title: string;
    location: string;
    bullets: string[];
  }[];
  projects: {
    name: string;
    tech: string;
    link: string;
    bullets: string[];
  }[];
  education: {
    school: string;
    date: string;
    degree: string;
    detail: string;
  }[];
  certifications: string[];
}

export function generateLaTeX(data: ResumeData): string {
  const esc = (s: string) =>
    s
      .replace(/\\/g, "\\textbackslash{}")
      .replace(/#/g, "\\#")
      .replace(/\$/g, "\\$")
      .replace(/%/g, "\\%")
      .replace(/&/g, "\\&")
      .replace(/_/g, "\\_")
      .replace(/\{/g, "\\{")
      .replace(/\}/g, "\\}")
      .replace(/~/g, "\\textasciitilde{}")
      .replace(/\^/g, "\\textasciicircum{}");

  const bullet = (s: string) =>
    `    \\resumeItem{${esc(s)}}`;

  const lines: string[] = [];

  lines.push(`%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ATS-OPTIMIZED RESUME`);
  lines.push(`% Generated by J-ATS Resume Builder`);
  lines.push(`%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%`);
  lines.push(``);
  lines.push(`\\documentclass[10pt,letterpaper]{article}`);
  lines.push(``);
  lines.push(`%----------PACKAGES----------`);
  lines.push(`\\usepackage[T1]{fontenc}`);
  lines.push(`\\usepackage[utf8]{inputenc}`);
  lines.push(`\\usepackage[empty]{fullpage}`);
  lines.push(`\\usepackage{enumitem}`);
  lines.push(`\\usepackage[hidelinks]{hyperref}`);
  lines.push(`\\usepackage{fancyhdr}`);
  lines.push(`\\usepackage{geometry}`);
  lines.push(``);
  lines.push(`%----------PAGE GEOMETRY----------`);
  lines.push(`\\geometry{`);
  lines.push(`    left=0.55in,`);
  lines.push(`    right=0.55in,`);
  lines.push(`    top=0.38in,`);
  lines.push(`    bottom=0.38in`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`%----------PAGE STYLE----------`);
  lines.push(`\\pagestyle{fancy}`);
  lines.push(`\\fancyhf{}`);
  lines.push(`\\fancyfoot{}`);
  lines.push(`\\renewcommand{\\headrulewidth}{0pt}`);
  lines.push(`\\renewcommand{\\footrulewidth}{0pt}`);
  lines.push(``);
  lines.push(`\\raggedbottom`);
  lines.push(`\\raggedright`);
  lines.push(`\\setlength{\\tabcolsep}{0in}`);
  lines.push(``);
  lines.push(`%----------SECTION COMMAND----------`);
  lines.push(`\\newcommand{\\resumeSection}[1]{%`);
  lines.push(`    \\vspace{6pt}%`);
  lines.push(`    {\\large\\scshape\\bfseries #1}%`);
  lines.push(`    \\vspace{2pt}%`);
  lines.push(`    \\hrule%`);
  lines.push(`    \\vspace{4pt}%`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`%----------CUSTOM COMMANDS----------`);
  lines.push(`\\newcommand{\\resumeItem}[1]{%`);
  lines.push(`    \\item\\small{#1\\vspace{-1pt}}%`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`\\newcommand{\\resumeSubheading}[4]{%`);
  lines.push(`    \\item`);
  lines.push(`    \\begin{tabular*}{\\textwidth}{l@{\\extracolsep{\\fill}}r}`);
  lines.push(`        \\textbf{#1} & #2 \\\\`);
  lines.push(`        \\textit{\\small#3} & \\textit{\\small#4} \\\\`);
  lines.push(`    \\end{tabular*}`);
  lines.push(`    \\vspace{-5pt}`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`\\newcommand{\\resumeProjectHeading}[2]{%`);
  lines.push(`    \\item`);
  lines.push(`    \\begin{tabular*}{\\textwidth}{l@{\\extracolsep{\\fill}}r}`);
  lines.push(`        \\textbf{#1} & #2 \\\\`);
  lines.push(`    \\end{tabular*}`);
  lines.push(`    \\vspace{-5pt}`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`\\newcommand{\\resumeSubHeadingListStart}{%`);
  lines.push(`    \\begin{itemize}[leftmargin=0.13in, label={}, itemsep=0pt, parsep=0pt, topsep=0pt]%`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`\\newcommand{\\resumeSubHeadingListEnd}{%`);
  lines.push(`    \\end{itemize}%`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`\\newcommand{\\resumeItemListStart}{%`);
  lines.push(`    \\begin{itemize}[leftmargin=0.18in, itemsep=0.5pt, parsep=0pt, topsep=1pt]%`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`\\newcommand{\\resumeItemListEnd}{%`);
  lines.push(`    \\end{itemize}%`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`%=====================================================================`);
  lines.push(`% DOCUMENT`);
  lines.push(`%=====================================================================`);
  lines.push(`\\begin{document}`);
  lines.push(``);
  lines.push(`%=====================================================================`);
  lines.push(`% HEADER`);
  lines.push(`%=====================================================================`);
  lines.push(`\\begin{center}`);
  lines.push(`    {\\LARGE \\textbf{\\scshape ${esc(data.header.name)}}}`);
  lines.push(`    \\vspace{2pt}`);
  lines.push(`    \\small`);

  const contactParts: string[] = [];
  if (data.header.phone) contactParts.push(data.header.phone);
  if (data.header.email)
    contactParts.push(
      `\\href{mailto:${data.header.email}}{${esc(data.header.email)}}`
    );
  if (data.header.website)
    contactParts.push(
      `\\href{https://${data.header.website}}{${esc(data.header.website)}}`
    );
  lines.push(`    ${contactParts.join(" \\;|\\; ")}`);

  lines.push(`    \\vspace{1pt}`);
  lines.push(`    \\small`);

  const linkParts: string[] = [];
  if (data.header.linkedin)
    linkParts.push(
      `\\href{https://${data.header.linkedin}}{${esc(data.header.linkedin)}}`
    );
  if (data.header.github)
    linkParts.push(
      `\\href{https://${data.header.github}}{${esc(data.header.github)}}`
    );
  if (data.header.leetcode)
    linkParts.push(
      `\\href{https://${data.header.leetcode}}{${esc(data.header.leetcode)}}`
    );
  if (linkParts.length > 0) lines.push(`    ${linkParts.join(" \\;|\\; ")}`);

  lines.push(`\\end{center}`);
  lines.push(``);

  // Summary
  if (data.summary) {
    lines.push(`%=====================================================================`);
    lines.push(`% SUMMARY`);
    lines.push(`%=====================================================================`);
    lines.push(`\\resumeSection{Summary}`);
    lines.push(`\\small{`);
    lines.push(esc(data.summary));
    lines.push(`}`);
    lines.push(``);
  }

  // Skills
  if (data.skills.length > 0) {
    lines.push(`%=====================================================================`);
    lines.push(`% TECHNICAL SKILLS`);
    lines.push(`%=====================================================================`);
    lines.push(`\\resumeSection{Technical Skills}`);
    lines.push(`\\resumeSubHeadingListStart`);
    data.skills.forEach((skill) => {
      lines.push(`    \\resumeItem{`);
      lines.push(`        \\textbf{${esc(skill.label)}} ${esc(skill.items)}`);
      lines.push(`    }`);
    });
    lines.push(`\\resumeSubHeadingListEnd`);
    lines.push(``);
  }

  // Experience
  if (data.experience.length > 0) {
    lines.push(`%=====================================================================`);
    lines.push(`% EXPERIENCE`);
    lines.push(`%=====================================================================`);
    lines.push(`\\resumeSection{Experience}`);
    lines.push(`\\resumeSubHeadingListStart`);
    data.experience.forEach((exp) => {
      lines.push(`    \\resumeSubheading`);
      lines.push(`        {${esc(exp.company)}}`);
      lines.push(`        {${esc(exp.date)}}`);
      lines.push(`        {${esc(exp.title)}}`);
      lines.push(`        {${esc(exp.location)}}`);
      lines.push(`    \\resumeItemListStart`);
      exp.bullets.forEach((b) => {
        if (b.trim()) lines.push(bullet(b));
      });
      lines.push(`    \\resumeItemListEnd`);
    });
    lines.push(`\\resumeSubHeadingListEnd`);
    lines.push(``);
  }

  // Projects
  if (data.projects.length > 0) {
    lines.push(`%=====================================================================`);
    lines.push(`% PROJECTS`);
    lines.push(`%=====================================================================`);
    lines.push(`\\resumeSection{Projects}`);
    lines.push(`\\resumeSubHeadingListStart`);
    data.projects.forEach((proj) => {
      const linkPart = proj.link ? ` \\;|; \\href{${proj.link}}{Link}` : "";
      lines.push(`    \\resumeProjectHeading`);
      lines.push(`        {\\textbf{${esc(proj.name)}} \\;|; \\emph{${esc(proj.tech)}}${linkPart}}`);
      lines.push(`        {}`);
      lines.push(`    \\resumeItemListStart`);
      proj.bullets.forEach((b) => {
        if (b.trim()) lines.push(bullet(b));
      });
      lines.push(`    \\resumeItemListEnd`);
    });
    lines.push(`\\resumeSubHeadingListEnd`);
    lines.push(``);
  }

  // Education
  if (data.education.length > 0) {
    lines.push(`%=====================================================================`);
    lines.push(`% EDUCATION`);
    lines.push(`%=====================================================================`);
    lines.push(`\\resumeSection{Education}`);
    lines.push(`\\resumeSubHeadingListStart`);
    data.education.forEach((edu) => {
      lines.push(`    \\resumeSubheading`);
      lines.push(`        {${esc(edu.school)}}`);
      lines.push(`        {${esc(edu.date)}}`);
      lines.push(`        {${esc(edu.degree)}}`);
      lines.push(`        {${esc(edu.detail)}}`);
    });
    lines.push(`\\resumeSubHeadingListEnd`);
    lines.push(``);
  }

  // Certifications
  if (data.certifications.length > 0) {
    lines.push(`%=====================================================================`);
    lines.push(`% CERTIFICATIONS & ACHIEVEMENTS`);
    lines.push(`%=====================================================================`);
    lines.push(`\\resumeSection{Certification \\& Achievements}`);
    lines.push(`\\resumeItemListStart`);
    data.certifications.forEach((cert) => {
      if (cert.trim()) lines.push(bullet(cert));
    });
    lines.push(`\\resumeItemListEnd`);
    lines.push(``);
  }

  lines.push(`\\end{document}`);

  return lines.join("\n");
}

export function downloadTex(content: string, filename: string) {
  const blob = new Blob([content], { type: "application/x-latex" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function getDefaultResumeData(): ResumeData {
  return {
    header: {
      name: "",
      phone: "",
      email: "",
      website: "",
      linkedin: "",
      github: "",
      leetcode: "",
    },
    summary: "",
    skills: [{ label: "Languages", items: "" }],
    experience: [],
    projects: [],
    education: [],
    certifications: [],
  };
}
